/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author fernando
 */
public class ViewBlocdeNotas extends javax.swing.JPanel {

    /**
     * Creates new form ViewBlocdeNotas
     */
    public ViewBlocdeNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfc_seleccionar_archivos = new javax.swing.JFileChooser();
        jsp_archivo = new javax.swing.JScrollPane();
        jta_archivo = new javax.swing.JTextArea();

        jfc_seleccionar_archivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfc_seleccionar_archivosActionPerformed(evt);
            }
        });

        jta_archivo.setColumns(20);
        jta_archivo.setRows(5);
        jsp_archivo.setViewportView(jta_archivo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jfc_seleccionar_archivos, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jsp_archivo, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsp_archivo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jfc_seleccionar_archivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jfc_seleccionar_archivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfc_seleccionar_archivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfc_seleccionar_archivosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JFileChooser jfc_seleccionar_archivos;
    public javax.swing.JScrollPane jsp_archivo;
    public javax.swing.JTextArea jta_archivo;
    // End of variables declaration//GEN-END:variables

    public void setTitle(String editor_de_Textto_MVC) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
